# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lm_cpp <- function(y, X) {
    .Call(`_MULTI_lm_cpp`, y, X)
}

MULTI_single <- function(DataList, r2 = 0.01, iter_times = 500L, ELBO_tol = 1e-6) {
    .Call(`_MULTI_MULTI_single`, DataList, r2, iter_times, ELBO_tol)
}

MULTI <- function(DataList, tissue_ref = "Tissue1", r2 = 0.01, cut_off = 0.5, iter_times = 500L, ELBO_tol = 1e-6) {
    .Call(`_MULTI_MULTI`, DataList, tissue_ref, r2, cut_off, iter_times, ELBO_tol)
}

rcpp_hello_world <- function() {
    .Call(`_MULTI_rcpp_hello_world`)
}

